#!/bin/bash
# This script was generated by classpath.py.
# It can be executed to do a "jar -xvf" for each jar in the
# CLASSPATH, so as to produce a list of all dependent classes for analysis.
# Chris Joakim, 2018/04/06


echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.0.0.RELEASE/spring-boot-starter-actuator-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.0.0.RELEASE/spring-boot-starter-actuator-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter/2.0.0.RELEASE/spring-boot-starter-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter/2.0.0.RELEASE/spring-boot-starter-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.0.0.RELEASE/spring-boot-starter-logging-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.0.0.RELEASE/spring-boot-starter-logging-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.10.0/log4j-to-slf4j-2.10.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.10.0/log4j-to-slf4j-2.10.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-api/2.10.0/log4j-api-2.10.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-api/2.10.0/log4j-api-2.10.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/yaml/snakeyaml/1.19/snakeyaml-1.19.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/yaml/snakeyaml/1.19/snakeyaml-1.19.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.0.0.RELEASE/spring-boot-actuator-autoconfigure-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.0.0.RELEASE/spring-boot-actuator-autoconfigure-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-actuator/2.0.0.RELEASE/spring-boot-actuator-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-actuator/2.0.0.RELEASE/spring-boot-actuator-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-context/5.0.4.RELEASE/spring-context-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-context/5.0.4.RELEASE/spring-context-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.4/jackson-datatype-jsr310-2.9.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.4/jackson-datatype-jsr310-2.9.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/micrometer/micrometer-core/1.0.1/micrometer-core-1.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/micrometer/micrometer-core/1.0.1/micrometer-core-1.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.10/HdrHistogram-2.1.10.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.10/HdrHistogram-2.1.10.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-thymeleaf/2.0.0.RELEASE/spring-boot-starter-thymeleaf-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-thymeleaf/2.0.0.RELEASE/spring-boot-starter-thymeleaf-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/thymeleaf/thymeleaf-spring5/3.0.9.RELEASE/thymeleaf-spring5-3.0.9.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/thymeleaf/thymeleaf-spring5/3.0.9.RELEASE/thymeleaf-spring5-3.0.9.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/thymeleaf/thymeleaf/3.0.9.RELEASE/thymeleaf-3.0.9.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/thymeleaf/thymeleaf/3.0.9.RELEASE/thymeleaf-3.0.9.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/attoparser/attoparser/2.0.4.RELEASE/attoparser-2.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/attoparser/attoparser/2.0.4.RELEASE/attoparser-2.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/unbescape/unbescape/1.1.5.RELEASE/unbescape-1.1.5.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/unbescape/unbescape/1.1.5.RELEASE/unbescape-1.1.5.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/thymeleaf/extras/thymeleaf-extras-java8time/3.0.1.RELEASE/thymeleaf-extras-java8time-3.0.1.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/thymeleaf/extras/thymeleaf-extras-java8time/3.0.1.RELEASE/thymeleaf-extras-java8time-3.0.1.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.0.0.RELEASE/spring-boot-starter-web-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.0.0.RELEASE/spring-boot-starter-web-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.0.0.RELEASE/spring-boot-starter-json-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.0.0.RELEASE/spring-boot-starter-json-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.4/jackson-datatype-jdk8-2.9.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.4/jackson-datatype-jdk8-2.9.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.4/jackson-module-parameter-names-2.9.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.4/jackson-module-parameter-names-2.9.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.7.Final/hibernate-validator-6.0.7.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.7.Final/hibernate-validator-6.0.7.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/classmate/1.3.4/classmate-1.3.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/classmate/1.3.4/classmate-1.3.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-web/5.0.4.RELEASE/spring-web-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-web/5.0.4.RELEASE/spring-web-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-beans/5.0.4.RELEASE/spring-beans-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-beans/5.0.4.RELEASE/spring-beans-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-webmvc/5.0.4.RELEASE/spring-webmvc-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-webmvc/5.0.4.RELEASE/spring-webmvc-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-aop/5.0.4.RELEASE/spring-aop-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-aop/5.0.4.RELEASE/spring-aop-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-expression/5.0.4.RELEASE/spring-expression-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-expression/5.0.4.RELEASE/spring-expression-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-spring-boot/2.0.1/azure-spring-boot-2.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-spring-boot/2.0.1/azure-spring-boot-2.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.0.0.RELEASE/spring-boot-autoconfigure-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.0.0.RELEASE/spring-boot-autoconfigure-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/json/json/20171018/json-20171018.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/json/json/20171018/json-20171018.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/projectlombok/lombok/1.16.20/lombok-1.16.20.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/projectlombok/lombok/1.16.20/lombok-1.16.20.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage-spring-boot-starter/2.0.1/azure-storage-spring-boot-starter-2.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage-spring-boot-starter/2.0.1/azure-storage-spring-boot-starter-2.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-spring-boot-starter/2.0.1/azure-spring-boot-starter-2.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-spring-boot-starter/2.0.1/azure-spring-boot-starter-2.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.0.0.RELEASE/spring-boot-starter-validation-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.0.0.RELEASE/spring-boot-starter-validation-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage/5.5.0/azure-storage-5.5.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage/5.5.0/azure-storage-5.5.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.4/jackson-core-2.9.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.4/jackson-core-2.9.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-core/0.8.0/azure-keyvault-core-0.8.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-core/0.8.0/azure-keyvault-core-0.8.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/session/spring-session-core/2.0.2.RELEASE/spring-session-core-2.0.2.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/session/spring-session-core/2.0.2.RELEASE/spring-session-core-2.0.2.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-jcl/5.0.4.RELEASE/spring-jcl-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-jcl/5.0.4.RELEASE/spring-jcl-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-devtools/2.0.0.RELEASE/spring-boot-devtools-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-devtools/2.0.0.RELEASE/spring-boot-devtools-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot/2.0.0.RELEASE/spring-boot-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot/2.0.0.RELEASE/spring-boot-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.0.0.RELEASE/spring-boot-starter-tomcat-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.0.0.RELEASE/spring-boot-starter-tomcat-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.28/tomcat-embed-core-8.5.28.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.28/tomcat-embed-core-8.5.28.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.28/tomcat-embed-el-8.5.28.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.28/tomcat-embed-el-8.5.28.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.28/tomcat-embed-websocket-8.5.28.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.28/tomcat-embed-websocket-8.5.28.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.0.0.RELEASE/spring-boot-starter-test-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.0.0.RELEASE/spring-boot-starter-test-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-test/2.0.0.RELEASE/spring-boot-test-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-test/2.0.0.RELEASE/spring-boot-test-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/2.0.0.RELEASE/spring-boot-test-autoconfigure-2.0.0.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/2.0.0.RELEASE/spring-boot-test-autoconfigure-2.0.0.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/junit/junit/4.12/junit-4.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/junit/junit/4.12/junit-4.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/assertj/assertj-core/3.9.1/assertj-core-3.9.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/assertj/assertj-core/3.9.1/assertj-core-3.9.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/mockito/mockito-core/2.15.0/mockito-core-2.15.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/mockito/mockito-core/2.15.0/mockito-core-2.15.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/bytebuddy/byte-buddy/1.7.10/byte-buddy-1.7.10.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/bytebuddy/byte-buddy/1.7.10/byte-buddy-1.7.10.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/bytebuddy/byte-buddy-agent/1.7.10/byte-buddy-agent-1.7.10.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/bytebuddy/byte-buddy-agent/1.7.10/byte-buddy-agent-1.7.10.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/skyscreamer/jsonassert/1.5.0/jsonassert-1.5.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/skyscreamer/jsonassert/1.5.0/jsonassert-1.5.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-core/5.0.4.RELEASE/spring-core-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-core/5.0.4.RELEASE/spring-core-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/springframework/spring-test/5.0.4.RELEASE/spring-test-5.0.4.RELEASE.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/springframework/spring-test/5.0.4.RELEASE/spring-test-5.0.4.RELEASE.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/xmlunit/xmlunit-core/2.5.1/xmlunit-core-2.5.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/xmlunit/xmlunit-core/2.5.1/xmlunit-core-2.5.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-documentdb/1.16.0/azure-documentdb-1.16.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-documentdb/1.16.0/azure-documentdb-1.16.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/uuid/java-uuid-generator/3.1.4/java-uuid-generator-3.1.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/uuid/java-uuid-generator/3.1.4/java-uuid-generator-3.1.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.4/jackson-databind-2.9.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.4/jackson-databind-2.9.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpcore/4.4.9/httpcore-4.4.9.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpcore/4.4.9/httpcore-4.4.9.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/webjars/bootstrap/3.3.7/bootstrap-3.3.7.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/webjars/bootstrap/3.3.7/bootstrap-3.3.7.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/webjars/jquery/2.1.4/jquery-2.1.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/webjars/jquery/2.1.4/jquery-2.1.4.jar >> doc/jar_contents.txt

