package org.cjoakim.azure.cosmos;

import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

/**
 * This class was generated by Spring Boot.
 *
 * Chris Joakim, Microsoft, 2018/04/11
 */

public class ServletInitializer extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(CosmosApplication.class);
	}

}
